# Generated by Django 4.2.7 on 2023-11-14 15:33

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruolo', models.CharField(max_length=100)),
                ('contributore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Contributi',
            },
        ),
        migrations.CreateModel(
            name='Progetto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100)),
                ('descrizione', models.TextField()),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('data_modifica', models.DateTimeField(auto_now=True)),
                ('link_progetto', models.CharField(blank=True, max_length=100)),
                ('stato', models.CharField(max_length=100)),
                ('autore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autore', to=settings.AUTH_USER_MODEL)),
                ('contributi', models.ManyToManyField(blank=True, to='progetti.contributo')),
            ],
            options={
                'verbose_name_plural': 'Progetti',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z ]*$', 'Solo caratteri alfanumerici.')])),
            ],
        ),
        migrations.CreateModel(
            name='Sviluppo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descrizione', models.TextField()),
                ('data_inizio', models.DateField(blank=True, null=True)),
                ('data_fine', models.DateField(blank=True, null=True)),
                ('stato', models.CharField(max_length=100)),
                ('progetto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='progetti.progetto')),
                ('responsabile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sviluppi',
            },
        ),
        migrations.AddField(
            model_name='progetto',
            name='tags',
            field=models.ManyToManyField(blank=True, to='progetti.tag'),
        ),
        migrations.CreateModel(
            name='Immagine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='images/')),
                ('progetto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='progetti.progetto')),
            ],
            options={
                'verbose_name_plural': 'Immagini',
            },
        ),
    ]
