# Generated by Django 4.2.7 on 2023-11-15 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progetti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progetto',
            name='data_creazione',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='progetto',
            name='data_modifica',
            field=models.DateField(auto_now=True),
        ),
    ]
